# @package _global_
defaults:
  - /model/base@planner_model
  - /agents/simple/search_agent@workers.SearchAgent
  - _self_

type: orchestrator

orchestrator_config:
  name: BaseOrchestratorAgent
  examples_path: plan_examples/chain.json  # default examples for task-decomposition. (in /utu/data/)
  add_chitchat_subagent: true  # add chitchat subagent

workers_info:
  - name: SearchAgent
    desc: information retrieval and data collection.
    strengths: Web search, information retrieval, research material collection, API data fetching
    weaknesses: No access to private databases, retrieval only (no content creation/modification)
